default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
